name: Build and Deploy to Cloud Run

on:
  push:
    branches:
    - master
    - develop
    - issue#[0-9]+[0-9]
    - release-[0-9]+.+[0-9]
  pull_request:
    types: [assigned, opened, synchronize, reopened]
  schedule:    
   - cron: '0 0 * * SUN'    

# Environment variables available to all jobs and steps in this workflow
env:
  PROJECT_ID: ${{ secrets.RUN_PROJECT }}
  RUN_REGION: us-east1
  SERVICE_NAME: unab-software-engineer-run

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      # Pipeline para Testing, ejecuta npm install automáticamente
      - name: Testing
        uses: stefanoeb/jest-action@1.0.2
        with: 
          jestArgs: --coverage test/ 
          
      # Configura sonarCloud
      - name: Inspección contínua
        uses: sonarsource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      

      # Setup gcloud CLI
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '275.0.0'
          service_account_email: ${{ secrets.SA_EMAIL }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS}}

      # Configure gcloud CLI
      - name: gcloud Set up
        run: |
          gcloud config set project $PROJECT_ID
      
      # Build and push image to Google Container Registry
      - name: Build
        run: |
          gcloud builds submit -t gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA

      # Deploy image to Cloud Run
      - name: Deploy
        run: |
          gcloud run deploy $SERVICE_NAME \
            --region $RUN_REGION \
            --image gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA \
            --platform managed
